export const meta = {
  name: 'build-workshops-wave-3',
  description: 'Wave 3 of add-workshops: 6 TDD builders on disjoint file sets (WP contracts, list + dateOperator filter, form, revisions + preview, event-screen gating, config), split integration (4 seam-closers, 1 verify runner), four review lenses, one fix agent',
  phases: [
    { title: 'Build', detail: '6 Opus builders, contract-first, TDD, disjoint files' },
    { title: 'Seams', detail: 'one Opus seam-closer per pair of touching builders' },
    { title: 'Verify', detail: 'one Fable runner reads only the failing output and gets pnpm run verify green' },
    { title: 'Review', detail: 'ADR · a11y/contrast/mobile · request budget (Opus) · legacy fidelity vs the D-list (Fable)' },
    { title: 'Fix', detail: 'one Fable agent applies confirmed findings and re-runs verify' },
  ],
}

const REPO = '/path/to/repo'
const APP = `${REPO}/apps/dashboard`
const PROPOSAL = `${REPO}/openspec/changes/add-workshops/proposal.md`
const DELTA_WP = `${REPO}/openspec/changes/add-workshops/specs/workshop-pages.md`
const DELTA_W = `${REPO}/openspec/changes/add-workshops/specs/workshops.md`
const SPEC = `${REPO}/docs/specs/spec-workshops/SPEC.md`
const EXTRACTION = '/path/to/docs/legacy/workshops.md'

const COMMON = `
You work in the dashboard monorepo at ${REPO}, branch feature/workshops, dashboard app at ${APP} (Nuxt 4, app/ srcDir). FIRST read ${REPO}/AGENTS.md in full — every rule there is binding: TDD (failing test first), 100% coverage, no code comments (names carry intent; only hidden invariants get a comment), generated wire types only (${REPO}/modules/contracts/src/generated/dashboard-api.ts is READ-ONLY), camelCase everywhere internally, Nullable<T>/Optional<T> from @org/contracts, Nuxt UI + FormKit (never UForm, never @formkit/themes), api calls only in use*Api composables, ONE upstream request per view asserted by a test, VueUse before hand-rolling, v-for renders a child component, mobile-first, dashboard styles are plain unlayered scoped CSS, same-name v-bind shorthand, docs verification for Nuxt 4 / Nuxt UI / FormKit (do not code from training data: use the nuxt MCP docs tools via ToolSearch, or ctx7).
WAVES 1 AND 2 ARE BUILT AND COMMITTED (entity, list, filters, six-step wizard, row actions, bulk actions, grid, import, statistics). The dashboard menu was ALSO rebuilt after the proposal was written: app/config/navigation.ts is now the LEGACY menu tree (25 top-level entries, a fixture in tests/config/navigation.test.ts asserts it verbatim), and it already holds a 'Workshop Pages' entry with status 'planned' at lines ~175–180. Wherever the proposal says "add a Workshop pages entry in the Tracks group", read: flip the EXISTING entry (and its 'Add Workshop Page' child) from 'planned' to 'ready' and keep the fixture in step. Nothing else about the menu changes.
READ ONLY THE LINE RANGES NAMED HERE, never a whole file unless it is under 200 lines:
- ${PROPOSAL}: W3.1 (lines 924–1039) and W3.2 (1040–1064) are THE CONTRACT — read both in full; the rows you consume from other agents are named by exact export/prop names there. "Where wave 1 leaves extension points" 1065–1087. Deviations D23, D26–D29 (1176–1215) and D47–D48 (1306–1325); D2 (1090–1110) for the named wire-type overrides. Agent plan wave 3 (1454–1470). Wave 3 tasks (1608–1645). Your own row of the plan is the ONLY set of files you may edit.
- ${DELTA_WP} whole (183 lines): the SHALL statements your tests prove. ${DELTA_W} "Feature flags" (405–425) for the gating rules.
- ${SPEC} "Wave 3" (531–640) for verbatim labels, help, options, permissions of the WP screens and the two gated wizard fields.
- ${EXTRACTION} §13 (2003–2293) for the WP screens verbatim, §10 (1616–1796) only for the event picker label template, §14 (2294–2366) for tags + the three flags, §16 (2428–2529) for permission strings. Never open the legacy repos (the original repos) or the live tenant.
Study the existing code you model on before writing — the Pages feature is the WP template (app/entities/page.ts, app/composables/api/usePagesApi.ts, app/pages/pages/**, app/schemas/page/**, app/tables/{page,pageFilters}.ts, app/composables/usePageFormData.ts and their specs tests/nuxt/{pages,pagesApi,pageForm,usePageFormData}.test.ts), the wave-1 workshops code for the flag composable (app/composables/useWorkshopFeatures.ts, app/composables/useWorkshopFormData.ts, app/entities/workshop.ts workshopIncludes), the filter bar (app/tables/filters.ts, app/components/Filter/**, tests/nuxt/listFilters.test.ts, tests/nuxt/workshopFilters.test.ts), route gating (app/utils/configAccess.ts, app/middleware/config.global.ts, tests/nuxt/routePermissions.test.ts, tests/nuxt/tracksRoutes.test.ts). Copy their conventions, helpers (tests/nuxt/helpers/**, mountWithUiStubs, until(), answer()) and test shapes exactly.
PARALLEL RULES — five other agents edit this working tree right now, each on a DISJOINT file set:
- Edit ONLY the files your row of the wave-3 agent plan lists (plus their tests). If you believe you must touch another file, do NOT: code to the contract and report the seam.
- Another agent's file may be missing or half-written while you work. Code against its CONTRACT (export names, signatures, props); if your test cannot run until it lands, write the test, stub locally inside the test only, and say so.
- Run ONLY your own tests: from ${APP}, \`pnpm exec vitest run <your test files>\` for plain specs and \`pnpm exec vitest run --config vitest.nuxt.config.ts <your test files>\` for tests/nuxt specs; lint only your files with \`pnpm exec eslint <files>\` from ${REPO} and \`pnpm exec stylelint <vue files>\`. Do NOT run the whole suite, full lint, nuxt typecheck or pnpm run verify. Do NOT git commit, stash, checkout or reset anything.
- Generated files are off-limits (a hook blocks writes).
RETURN A COMPACT REPORT, under 60 lines, no code, no test output, no narration: files created/changed; test files and, one line each, what they assert; every deviation from the contract or ambiguity (what you chose, citing § or D); the seams (cross-agent imports you could not verify, tests you stubbed).
`

const BUILDERS = [
  { key: 'A', name: 'contracts', prompt: `YOU ARE W3-A (WP contracts). Own: app/entities/workshopPage.ts (WorkshopPage, WorkshopPagePayload, WorkshopPageRevision if the revisions api needs a named type, workshopPageResource, WORKSHOP_PAGE_INCLUDES; contentBlocks through toBlockDocument / persistedDocument exactly as entities/page.ts does), app/composables/api/useWorkshopPagesApi.ts (search, view, create, update, destroy(id, force?), searchRevisions, viewRevision, restoreRevision, viewPreview, updatePreview — usePagesApi is the shape; updatePreview PUTs toPayload's body and returns void from the 204, reading no body), app/composables/api/useWorkshopTagsApi.ts (read-only { search, view }; the autocomplete sends filter[name], not filter[search] — §14), app/constants/entities.ts (ENTITIES.workshopPage already exists — confirm its labels, routes and permission strings match SPEC/§16 and complete anything missing; you are the only agent in this file), app/utils/workshopPageListQuery.ts (WorkshopPageQuery = ListQuery; listQuery(query, { defaultSort: '-updated_at', tieBreaker: '-id' })). Tests: tests/nuxt/workshopPagesApi.test.ts (exact urls, methods, includes, query keys for every method; destroy force flag; updatePreview body = payload and no body read), tests/nuxt/workshopTagsApi.test.ts (filter[name]), tests/utils/workshopPageListQuery.test.ts, and an entity spec (wire → view model and payload round trip; the D2 named overrides carry their TODO). Find the exact routes and shapes in the generated dashboard-api.ts (grep workshop-page) and in ${EXTRACTION} §17 (2530–2707).` },
  { key: 'B', name: 'list-filters', prompt: `YOU ARE W3-B (WP list + dateOperator filter). Own: app/pages/workshop-pages/index.vue (definePageMeta can + features: ['workshop-page']; no selection prop, so no select column and no bulk bar; a row's View action from type + workshopId — /event/{id} for pre-event, /boxscore/{id} for post-event, absent without an event — D27), app/tables/workshopPage.ts (the seven columns of W3.1 in order + ACTIONS_COLUMN), app/tables/workshopPageFilters.ts (the eight filters of W3.1; search is the bar's own pill), app/composables/useWorkshopPages.ts (fetchWorkshopPages), app/components/WorkshopPage/{TitleCell,TypeCell,WorkshopCell}.vue with the props of the W3.1 component table, AND the dateOperator FilterKind (D48): app/tables/filters.ts gains the kind, app/components/Filter/Control.vue a branch, app/components/Filter/DateOperator.vue is a new pill with one datetime input and a fixed '>=' operator whose VALUE is the single string the query carries (filtersToQuery unchanged). Tests: tests/config/workshopPage.test.ts (columns), tests/config/workshopPageFilters.test.ts, tests/nuxt/workshopPages.test.ts (ONE request on mount with the include set of the columns; default sort -updated_at; the three date filters send one key each with the operator in the value, e.g. filter[published_at]=>=…; the Workshop picker asks for include=track.topic,track.year and sort -datetime; View href per type and absent without event; no select column), a DateOperator pill spec, and the EXISTING filter-bar specs tests/nuxt/listFilters.test.ts, tests/nuxt/workshopFilters.test.ts and every other spec that touches Filter/Control.vue kept green. W3-A's api/entity/list-query may not exist yet: code to their names; W3-C's useWorkshopPageFormData supplies workshopOptions/loadWorkshop for the FORM, so the LIST's entity filter loaders (optionsKey workshopOptions / loaderKey loadWorkshop, authorOptions / loadAuthor) follow how app/pages/pages/index.vue and app/tables/pageFilters.ts wire theirs.` },
  { key: 'C', name: 'form', prompt: `YOU ARE W3-C (WP form). Own: app/schemas/workshopPage/{general,contentBlocks}.ts + index.ts exporting workshopPageSchema: EntitySchema whose form is one FormTabs with General, Content and one FormTab per ContentZoneStep (D28, minimum two steps), app/pages/workshop-pages/new.vue and app/pages/workshop-pages/[id]/index.vue (can declarations from ENTITIES.workshopPage, features: ['workshop-page'], numeric validate on the record route; the create pre-fill from ?workshop_id=&type=; the not-linked banner verbatim from §13; the second live page of one type surfaces the api's 422 on the form; the record page HOSTS the header 'Revisions {n}' control and the footer 'Preview' button that W3-D supplies — render them by their contract: the header control links to /workshop-pages/{id}/revisions and shows the count, the Preview button calls W3-D's useWorkshopPagePreview(id).preview(values) and is gated on 'Update workshop page preview revision' and disabled while the form is invalid; stub W3-D's composable in your spec if it has not landed and say so), app/composables/useWorkshopPageFormData.ts (the W3.1 interface: workshopOptions / loadWorkshop with sort ['-datetime'], include ['track.topic','track.year'], the §10 label template, search only — D47; tags: ['workshop_page']; zoneSteps), app/composables/useContentZoneSteps.ts (ContentZoneStep { key; label; order }; one entry per zone configured for WorkshopPage, ordered by the zone's own order, labelled from its own label, [] when none; find where the website config exposes content zones — grep contentZones / zones in app/ and the generated spec; a zone step nests contentZones → <key> → contentBlocks and IS strict against that zone's block set; the Content step is NOT strict and falls back to the tag allowlist). Tests: tests/config/workshopPageSchemas.test.ts, tests/nuxt/workshopPageForm.test.ts (exactly two steps with no zones; one extra step per configured zone in configuration order and labels; zone step strict, Content step tag allowlist; ?workshop_id=&type= pre-fill; the banner; 422 surfaced; create sends ONE POST with the payload; edit loads ONE view request with the include set and PUTs once; preview gate/disabled states), tests/nuxt/useWorkshopPageFormData.test.ts (option label template, include, sort, search-only), tests/nuxt/useContentZoneSteps.test.ts.` },
  { key: 'D', name: 'revisions-preview', prompt: `YOU ARE W3-D (revisions + preview). Own: app/pages/workshop-pages/[id]/revisions.vue (can 'View workshop page' plus whatever §16 names for revisions, features: ['workshop-page'], numeric validate; ONE searchRevisions request on mount; view a revision; restore-a-revision through restoreRevision with confirmation, then refresh), app/components/WorkshopPage/RevisionList.vue (props { revisions; loading; canView; canRestore }, emits view(id) / restore(id); a v-for renders a child row component if the row has more than a trivial leaf; skeleton with aria-busy while loading — ADR-020), app/composables/useWorkshopPagePreview.ts (the W3.1 signature: previewing, error, preview(values) PUTs the preview revision with the SAME payload a save builds through W3-A's updatePreview and then opens /preview/workshop-page/{id} in a NAMED window reused across presses — use window.open with a fixed name, no VueUse equivalent exists for a named target). Tests: tests/nuxt/workshopPageRevisions.test.ts (one request on mount; view/restore permissions hide the controls; restore confirms then posts once and refetches; skeleton), tests/nuxt/workshopPagePreview.test.ts (PUTs the save payload once; reads no body from the 204; opens the named window once per press with the same name; error surfaced; previewing flag). The record page that renders your composable's button and the 'Revisions {n}' header link is W3-C's; you do not touch it. W3-A's api may not exist: code to updatePreview(id, data) => Promise<void>, searchRevisions, viewRevision, restoreRevision by name and stub in your spec if needed.` },
  { key: 'E', name: 'event-gating', prompt: `YOU ARE W3-E (event-screen gating). Own: app/components/Workshop/PageBadges.vue (props { preEventPage?: unknown; postEventPage?: unknown }), app/components/Workshop/PageActions.vue (props { eventId: string; preEventPage?: unknown; postEventPage?: unknown; canCreate: boolean }, deep-linking to /workshop-pages/new?workshop_id={id}&type=pre-event|post-event, and to the existing page's edit route when one exists — follow §13.1), app/schemas/workshop/links.ts (RE-OPENED from wave 1: APPEND the Tags field and its 'Add Workshop Tag' button gated on $isTagFeatureEnabled and on 'Create workshop tag' — D23; every existing spec of that schema stays green), and the two host edits you own ALONE this wave: the #speakerName-cell slot of app/pages/workshops/index.vue rendering PageBadges next to the speaker, and the wizard header of app/pages/workshops/[id].vue rendering PageActions — all three (badges, buttons, the two extra includes via useWorkshopFeatures().pageIntegration and workshopIncludes(features)) require the flag AND 'View workshop page' (§13.1, DELTA "Feature flags"). Tests: tests/nuxt/workshopPageGating.test.ts (flag OFF: no badges, no buttons, the list's include holds exactly two relations; flag ON + permission: badges, buttons, four relations; flag ON without 'View workshop page': none of it; the deep links' exact hrefs), extend the links-step schema spec (Tags field present only with the flag; Add button only with the flag and the create permission), and keep tests/nuxt/workshops.test.ts and tests/nuxt/workshopForm.test.ts green, in particular their ONE-request assertions. Check app/composables/useWorkshopFeatures.ts and useWorkshopFormData.ts (tagOptions / isTagFeatureEnabled) and the workshopTags branch of app/utils/workshopPayload.ts before writing — they are the extension points wave 1 left for you and are NOT to be reshaped.` },
  { key: 'F', name: 'config-routes', prompt: `YOU ARE W3-F (config + route tests). Own: app/config/navigation.ts (flip the existing 'Workshop Pages' entry and its 'Add Workshop Page' child from status 'planned' to 'ready' — nothing else; can 'View-all workshop pages', feature 'workshop-page' are already there), tests/config/navigation.test.ts (the LEGACY_MENU fixture and any planned/ready expectations move with it — keep the file's structure, it is the verbatim legacy assertion), app/config/dictionaries.ts (the Workshop Tags entry's feature corrected from 'workshop-tags' to 'workshop-tag' — D26 — and the dictionaries spec tests/nuxt/dictionaries.test.ts / tests/config/* that reads it), and the route tests: extend tests/nuxt/routePermissions.test.ts (or a new tests/nuxt/workshopPageRoutes.test.ts modelled on tests/nuxt/tracksRoutes.test.ts) asserting that with the flag OFF there is no menu entry and every /workshop-pages* url REDIRECTS to the dashboard home through the EXISTING resolveConfigRedirect (D29 revised — app/utils/configAccess.ts and app/middleware/config.global.ts are NOT edited), that with the flag ON a permission refusal on the same routes is a 403, and that a user holding only 'View-all workshop pages' + 'View workshop page' reaches the list and the two record routes. The page files are W3-B/C/D's; your tests import them by path and may need to wait for them — write the tests to the contract (routes and their can/features meta per W3.1) and stub what has not landed, saying so. The featured-route check in routePermissions.test.ts already generalises 'a featured ready entry's static route declares the same features meta' — flipping the entry to ready makes that check bite on the WP pages; report it as a seam if the pages are missing when you run.` },
]

phase('Build')
const builds = await parallel(BUILDERS.map((b) => () =>
  agent(`${COMMON}\n${b.prompt}`, { label: `build:W3-${b.key}-${b.name}`, phase: 'Build', model: 'opus', effort: 'medium' })))
const report = (i) => builds[i] ?? 'NO REPORT (agent failed)'
log(`builders done: ${builds.filter(Boolean).length}/${BUILDERS.length}`)

phase('Seams')
const PAIRS = [
  ['A', 'B', 'W3-B consumes W3-A: workshopPageResource / WORKSHOP_PAGE_INCLUDES, useWorkshopPagesApi.search, workshopPageListQuery, ENTITIES.workshopPage. Shared files: entities/workshopPage.ts, composables/api/useWorkshopPagesApi.ts, composables/useWorkshopPages.ts, pages/workshop-pages/index.vue, tables/workshopPage*.ts and their specs.'],
  ['A', 'C', 'W3-C consumes W3-A: WorkshopPagePayload, toPayload / the entity mappers, useWorkshopPagesApi.{view,create,update}, useWorkshopTagsApi for the tags allowlist, ENTITIES.workshopPage permissions. Shared files: entities/workshopPage.ts, both api composables, schemas/workshopPage/**, pages/workshop-pages/{new,[id]/index}.vue, composables/useWorkshopPageFormData.ts and their specs.'],
  ['C', 'D', 'W3-C hosts W3-D: the record page renders the Revisions {n} header control and the Preview footer button, calling useWorkshopPagePreview(id).preview(values) with the SAME payload a save builds; W3-D calls W3-A updatePreview / searchRevisions / viewRevision / restoreRevision (read W3-A\'s file for the names, its report is not given to you). Shared files: pages/workshop-pages/[id]/{index,revisions}.vue, composables/useWorkshopPagePreview.ts, components/WorkshopPage/RevisionList.vue and their specs.'],
  ['E', 'F', 'W3-F\'s route tests import W3-B/C/D pages and assert the flag-off redirect, the 403 and the view-only reach; W3-E gates badges/buttons/includes on the same flag + permission and the navigation entry W3-F flipped now makes the featured-route check bite on the WP pages. Shared files: config/navigation.ts, config/dictionaries.ts, tests/config/navigation.test.ts, tests/nuxt/routePermissions.test.ts, the new route spec, tests/nuxt/workshopPageGating.test.ts, schemas/workshop/links.ts and the two workshops host pages. Read W3-B/C/D\'s page files directly for their meta.'],
]
const idx = (k) => BUILDERS.findIndex((b) => b.key === k)
const seams = await parallel(PAIRS.map(([x, y, scope]) => () =>
  agent(`${COMMON}
YOU ARE THE SEAM-CLOSER FOR W3-${x} ↔ W3-${y}. The builders are done. Three other seam-closers work on OTHER pairs right now, so: touch ONLY the shared files of your pair named below plus the two builders' own files; do not run the whole suite, only the specs of your two builders (from ${APP}: pnpm exec vitest run <files> and --config vitest.nuxt.config.ts <files>) and eslint/stylelint on the files you edit. Close every seam the two reports name and every one the code shows: missing exports, name mismatches against the contract (the proposal wins when two builders disagree), stubs left in tests that the real file can now replace, type errors visible in the shared files. Do NOT commit.
Scope: ${scope}
Report of W3-${x}:
${report(idx(x))}
Report of W3-${y}:
${report(idx(y))}
Return under 30 lines: seams closed (file → what), seams you could NOT close and why, specs of the pair now green / still red with the failing test names only.`, { label: `seam:W3-${x}-${y}`, phase: 'Seams', model: 'opus', effort: 'medium' })))
log(`seam-closers done: ${seams.filter(Boolean).length}/${PAIRS.length}`)

phase('Verify')
const verified = await agent(`${COMMON}
YOU ARE THE VERIFY RUNNER and run alone in the tree. The six builders and four seam-closers are done; you do NOT receive their reports — the tree and the gate output are your inputs. Job: get \`pnpm run verify\` green from ${REPO} (lint, stylelint, typecheck, tests at 100% coverage, script + lint-rule suites, contrast gate). Token discipline: run each stage with its output redirected to a file under ${REPO}/.claude-flow/data/add-workshops/ (mkdir -p), then read ONLY the failing part (grep -nE "FAIL|✗|×|error|Error|threshold|✖" and the surrounding lines); never cat a whole passing log. Fix what fails at the cause: cross-agent name mismatches (the proposal's W3.1/W3.2 contract wins), leftover test stubs, type errors, coverage holes (write the missing test, never an exclusion), contrast pairs (add the pair to scripts/lib/contrastGate.ts). Known load-sensitive specs that pass alone but can race under the full coverage run: tests/nuxt/bulkEdit.test.ts ('keeps a rejected row dirty'), the tickets picker in tests/nuxt/navigation.test.ts, the step-rail tally in tests/nuxt/formTabSteps.test.ts — re-run such a file ALONE before treating a red as real, and say which you re-ran. When verify is green, walk the Wave 3 task checklist in ${PROPOSAL} (lines 1608–1645) and tick each box you can confirm from the tree (Edit tool); leave the 'gate' and 'verification' boxes for the human. Do NOT run verify:release, do NOT commit.
Seam-closer notes, failing tests only:
${seams.map((s, i) => `- W3-${PAIRS[i][0]}↔${PAIRS[i][1]}: ${s ?? 'no report'}`).join('\n')}
Return under 40 lines: pass/fail per verify stage at the end, the coverage figure, what you fixed (file → cause), which load-sensitive specs you re-ran alone, task boxes you could not tick and why, anything a reviewer should look at first.`, { label: 'verify:W3', phase: 'Verify', model: 'fable', effort: 'high' })

phase('Review')
const FINDINGS = {
  type: 'object',
  properties: {
    findings: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          file: { type: 'string' },
          line: { type: 'integer' },
          severity: { type: 'string', enum: ['blocker', 'major', 'minor'] },
          rule: { type: 'string', description: 'The ADR, AGENTS.md rule, extraction § or proposal D number the finding cites' },
          claim: { type: 'string' },
          evidence: { type: 'string' },
          fix: { type: 'string' },
        },
        required: ['file', 'severity', 'rule', 'claim', 'evidence', 'fix'],
      },
    },
  },
  required: ['findings'],
}
const LENSES = [
  ['adr', 'opus', 'medium', 'ADR COMPLIANCE over every file wave 3 added or changed: ADR-012 (no hand-written wire types beyond the D2 named overrides, each with its TODO), ADR-013 (camelCase internally; snake only at the typed client; no manual JSON.stringify), ADR-014 (one upstream request per view asserted; no cache:no-cache; no N awaited composables; no per-row lookups; preview PUTs once and reads no body), ADR-009 (FormKit engine, U* presentation, no UForm; the dynamic zone steps are FormKit groups), ADR-011 (v-for renders a child component; granularity), ADR-020 (skeletons with aria-busy for anything loading in the browser — the revisions list, the WP list), AGENTS.md style rules (no comments except hidden invariants, Nullable<T> import, same-name v-bind shorthand, VueUse before hand-rolling, mobile-first CSS, unlayered scoped CSS in dashboard), the menu rules (navigation.ts is the legacy tree; entries flip planned→ready, never get added or moved). Cite file:line and the rule.'],
  ['a11y', 'opus', 'medium', 'A11Y, CONTRAST, MOBILE-FIRST over the WP list, the dateOperator pill, the WP wizard with its dynamic steps (the step rail must announce the added steps; the not-linked banner is perceivable), the revisions screen (restore confirmation semantics, skeleton aria-busy), the Preview button (disabled reason exposed), PageBadges/PageActions in the event screens (badges are not colour-only; buttons have accessible names naming pre/post-event): base styles are mobile and larger breakpoints use md:/lg:, no desktop-first max-* queries; every colour token used by new text/badges is paired in scripts/lib/contrastGate.ts (run pnpm run test:scripts to confirm); every input has an accessible name.'],
  ['budget', 'opus', 'medium', 'REQUEST BUDGET. For the WP list, the WP create and edit pages, the revisions page and the two changed workshops screens: read the page, its composables and its test, count the upstream requests actually issued on mount and on each interaction (filter/sort/page change, save, preview, restore, the event picker search), and confirm the test asserts that exact count and include set (ADR-014). Flag any request the user did not ask for (mount-time refetch, option lists on load, a lookup per row, a double fetch on filter change, the two extra includes sent when the flag is off or the permission is missing) and any picker that does not debounce through VueUse.'],
  ['fidelity', 'fable', 'high', 'LEGACY FIDELITY of the WP screens and the two gated wizard fields against §13, §14 and §16 of the extraction and the Wave 3 section of SPEC.md (531–640), judged with the D-list (D23, D26–D29, D47, D48 and any other D the code cites) in hand. Compare column set/order/labels, the eight filters and their keys (the three date filters as ONE key whose value carries >=), the wizard steps (General, Content, one per zone — D28), every label/help/option/validation string, the not-linked banner, the pre-fill from ?workshop_id=&type=, the View action (D27), the revisions and preview behaviour (§13), the gating matrix (flag AND View workshop page for badges/buttons/includes; flag AND Create workshop tag for the Add button — D23), the dictionary feature name (D26), the redirect-not-403 for flag-off urls (D29 revised), the tags picker filter[name] (§14), the navigation entry (must be the legacy entry flipped to ready, not a new one). Every difference from legacy must be a numbered deviation in the D-list (1088–1363); any difference NOT there is a finding (blocker if a label/option/permission is wrong or a column/field/step is missing; major if a condition, order or default differs). Also check each cited D was implemented as written. Cite § or D in rule.'],
]
const reviews = await parallel(LENSES.map(([key, model, effort, lens]) => () =>
  agent(`${COMMON}
YOU ARE A REVIEWER, lens: ${lens}
Scope: \`git status --short\` and \`git diff --stat\` in ${REPO} list everything wave 3 touched (waves 1–2 and the menu are committed; review only the UNCOMMITTED work, reading committed files only as context). Read the code and the diff, not any report. Report ONLY findings you can evidence with file:line and a rule/section citation; give a concrete fix each. Do not edit anything. Return the findings list only.
`, { label: `review:${key}`, phase: 'Review', model, effort, schema: FINDINGS })))
const findings = reviews.filter(Boolean).flatMap((r) => r.findings)
log(`review findings: ${findings.length} (${findings.filter((f) => f.severity === 'blocker').length} blockers, ${findings.filter((f) => f.severity === 'major').length} major)`)

phase('Fix')
const fixed = await agent(`${COMMON}
YOU ARE THE FIX AGENT and run alone in the tree. Adversarial review produced these findings (JSON); each cites a rule — an ADR, an AGENTS.md rule, an extraction § or a proposal D number — read the cited rule/section yourself before acting, not the reviewer's reasoning:
${JSON.stringify(findings, null, 2)}
Verify each against the code and the cited rule; apply every blocker and major, and cheap minors; reject a wrong finding with a reason. A finding that asks for a behaviour the proposal's D-list (1088–1363) forbids, or that would add or move a menu entry, or that would edit configAccess.ts / config.global.ts (D29 revised), is rejected, not applied. Then run \`pnpm run verify\` from ${REPO} until green (100% coverage), redirecting each stage to a file under ${REPO}/.claude-flow/data/add-workshops/ and reading only the failing part; re-run a known load-sensitive spec alone before treating it as red (bulkEdit 'keeps a rejected row dirty', the navigation tickets picker, the formTabSteps tally). Do NOT commit.
Return under 50 lines: numbered finding → applied / rejected (reason); the verify pass/fail per stage and coverage figure; and a 10-line summary for the human of what wave 3 delivers and what to look at in the browser (urls, states; note that the test tenant has all three flags OFF so only flags-off rendering is provable there).
`, { label: 'fix', phase: 'Fix', model: 'fable', effort: 'high' })

return { builds: BUILDERS.map((b, i) => `W3-${b.key} ${b.name}: ${report(i)}`), seams, verified, findings, fixed }